name: Release Nuget Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.102'

      - name: Install NuGet Client
        uses: nuget/setup-nuget@v1

      - name: Remove Github NuGet Source
        run: dotnet nuget remove source localPackages

      - name: Add Github NuGet Source
        run: dotnet nuget add source --username byCrookie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/byCrookie/index.json"

      - name: Test
        run: dotnet test --verbosity normal
        
      - name: Generate Nuget Packages
        run: dotnet pack -c Release -o packages\ --include-source --include-symbols -p:IsLocalBuild=false

      - name: Push NuGet Packages To Github Packages
        run: nuget push .\packages\*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source github -SkipDuplicate
